openapi: '3.0.0'
info:
  title: GNS-ERP
  version: 1.0.0
  description: >
    ## Пагинация

    Каждый GET запрос к справочнику возвращает только 15 результатов с определенной страницы. Что-бы указать страницу<br>
    добавьте в запрос параметр `page`. Общее количество страниц указано в массиве `meta`.


    Каждый запрос с пагинацией принимает опциональный параметр `perPage`, означающий желаемое количество записей на<br>
    одной странице.

    ## Фильтрация

    Каждый GET запрос к справочнику может содержать параметры для фильтрации. Пример:<br>
    `GET /api/inventory?serial=NB-2555&category=1|4|5`<br>

    Этот запрос возвращает только те данные где поле `serial` содержит текст `NB-2555`, а ID категории равно `1`, `4` или `5`.

    ## Сортировка

    Каждый GET запрос к справочнику может содержать параметры для сортировки в виде массива. Пример:<br>
    `GET /api/user?sort[0][field]=name&sort[0][order]=asc`<br>

    Этот запрос сортирует данные полученные из справочника `user` по полю `name` по возрастанию.


    Возможна мультисортировка Пример:<br>
    `GET /api/user?sort[0][field]=name&sort[0][order]=asc&sort[1][field]=email&sort[1][order]=desc`<br>

    Этот запрос сначала сортирует данные полученные из справочника `user` по полю `name` по возрастанию,
    а затем сортирует по полю `email` по убыванию.

    ## Переходы статусов в запросах на закупку/перевозку

    Иногда требуются дополнительных параметров, которые не описаны в этой доке т.к. пришлось бы создавть отдельный метод на каждый переход статуса.
    Что-бы узнать требуемые параметры сделайте пустой запрос и посмотрите какие поля будут требоваться.

    ## Проблема с передачей данных в PUT.

    Иногда при передаче данных в `form-data` при помощи метода `PUT` сервер может не увидеть данные. В таком
    случае следует отправлять запрос при помощи метода `POST`, добавив в `params` переменную `_method='PUT'`.
    С целью предупреждения бага можно отправлять все PUT запросы вышеописанным способом.

    ## Удаление привязанных объектов.

    Иногда при попытке удаления какого-либо объекта можно получить ответ с кодом 409:

    ```

    {
        "message": "Trying to delete important attached record."
    }

    ```

    Это значит что объект нельзя удалить пока не будут удалены другие связанные с ним объекты.
    Например нельзя удалить локацию на которое едет оборудование в составе MR или SR.


    [Параметры для статусов MR](/storage/api-docs/crud/materialRequest/states/statuses.md)

    [Параметры для статусов SM](/storage/api-docs/crud/shipmentRequest/states/statuses.md)

    [Типы нотификаций](/storage/api-docs/notifications/types.md)

servers:
  - url: /api
  - url: http://localhost:8098/api
security:
  - bearerAuth: [ ]
